spring:
  application:
    name: sampleAI
#  main:
#    web-application-type: none
  ai:
#    mcp:
#      client:
#        enabled: true
#        name: my-mcp-client
#        version: 1.0.0
#        request-timeout: 30s
#        type: ASYNC  # or ASYNC for reactive applications
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8081
    openai:
      api-key: ${OPENAI_API_KEY}
